### PR TITLE
286 add eol breaks

### LINKED ISSUE #286: End of line breaks at the end of each file.
Some Files don't have end of line breaks at the end of the file. Github throws a warning and there are some other things which can be avoided with an EOL Break.

### PR DESCRIPTION
**Pull request by xsaschako**
## Merge Request - GuideLine Checklist 

**Guideline** to check code before resolve WIP and approval, respectively.
As many checkboxes as possible should be ticked.

### Checks by code author:
* [x] There is at least one issue associated with the pull request.
* [x] The branch follows the naming conventions as defined in the [git workflow](git-workflow).
* [x] New code adheres with the [coding guidelines](coding-guidelines)
* [x] Tests for new functionality has been added
* [x] A local test was succesful
* [x] There is appropriate **documentation** of your work. (use doxygen style comments)
* [x] If new third party software is used, did you pay attention to its license? Please remember to add it to the wiki after successful merging.
* [x] If new mathematical methods or epidemiological terms are used, has the glossary been updated ? Did you provide further documentation ?
 is present or referenced. Please provide your references.
* [x] The following questions are addressed in the documentation*:  Developers (what did you do?, how can it be maintained?), For users (how to use your work?), For admins (how to install and configure your work?)
* For documentation: Please write or update the Readme in the current working directory!

### Checks by code reviewer(s):
* [x] Is the code clean of development artifacts e.g., unnecessary comments, prints, ...
* [x] The ticket goals for each associated issue are reached or problems are clearly addressed (i.e., a new issue was introduced).
* [x] There are appropriate **unit tests** and they pass.
* [x] The git history is clean and linearized for the merge request.
* [x] Coverage report for new code is acceptable. 

closes #286

### CODE REVIEW

**Comment by dabele** [comment]
Is this done or still WIP? If done, please resolve merge conflicts and mark as ready

**Comment by xsaschako** [comment]
It's wip but only a few things need to be added

**Review by dabele — DISMISSED** [review]

**Comment by dabele** [comment]
merge conflicts need to be resolved.

**Comment by xsaschako** [comment]
@dabele Sorry, rebased, so i force pushed the files. This supposedly needs your review (again).

**Pull request merged**
