### PR TITLE
353 upgrade python modules

### LINKED ISSUE #353: Upgrade numpy version
Numpy version 1.21 cause a security warning, so it should be updated to >=1.22.
Numpy 1.22 does not support python 3.7 officially. This also needs to be changed then.

### PR DESCRIPTION
**Pull request by patricklnz**
Numpy had to be updated due to a security warning (from >=1.21 to >=1.22).
The new numpy version does not support Python 3.7 and this is updated to 3.8.
Pandas Version 1.4 had a view errors and warnings.

## Merge Request - GuideLine Checklist 

**Guideline** to check code before resolve WIP and approval, respectively.
As many checkboxes as possible should be ticked.

### Checks by code author:
* [x] There is at least one issue associated with the pull request.
* [x] The branch follows the naming conventions as defined in the [git workflow](git-workflow).
* [x] New code adheres with the [coding guidelines](coding-guidelines)
* [ ] Tests for new functionality has been added
* [x] A local test was succesful
* [x] There is appropriate **documentation** of your work. (use doxygen style comments)
* [ ] If new third party software is used, did you pay attention to its license? Please remember to add it to the wiki after successful merging.
* [ ] If new mathematical methods or epidemiological terms are used, has the glossary been updated ? Did you provide further documentation ?
 is present or referenced. Please provide your references.
* [ ] The following questions are addressed in the documentation*:  Developers (what did you do?, how can it be maintained?), For users (how to use your work?), For admins (how to install and configure your work?)
* For documentation: Please write or update the Readme in the current working directory!

### Checks by code reviewer(s):
* [ ] Is the code clean of development artifacts e.g., unnecessary comments, prints, ...
* [ ] The ticket goals for each associated issue are reached or problems are clearly addressed (i.e., a new issue was introduced).
* [ ] There are appropriate **unit tests** and they pass.
* [ ] The git history is clean and linearized for the merge request.
* [ ] Coverage report for new code is acceptable. 

Closes #353 and #229.

### CODE REVIEW

**Review by mknaranja — APPROVED** [review]
Thank you @patricklnz . Well done :)

**Comment by xsaschako** [comment]
Sorry I couldn't do a review! I saw that python was updated to 3.8. one comment: as I was looking up the actual release of python the current development of python 3.11 is promising a lot of improvements performance wise, see [https://docs.python.org/3/whatsnew/3.11.html](python 3.11 doc).
Maybe we could see if we can upgrade to this version. :-)

**Comment by mknaranja** [comment]
@xsaschako We also support multiple versions of python, see https://github.com/DLR-SC/memilio/blob/main/.github/actions/build-py/action.yml#L22-L23. Now the minimal version changed but we could do a test for python 3.11 in the future. Maybe make it an issue?

**Comment by xsaschako** [comment]
> @xsaschako We also support multiple versions of python, see https://github.com/DLR-SC/memilio/blob/main/.github/actions/build-py/action.yml#L22-L23. Now the minimal version changed but we could do a test for python 3.11 in the future. Maybe make it an issue?

Ah, yes! I have a vague memory of some python versions not working. I'll investigate it after Stuttgart or when I'm free. Also, I'll open an issue.

**Pull request merged**
