### PR TITLE
342 extend and improve tools to visualize simulation results

### PR DESCRIPTION
**Pull request by mknaranja**
## Merge Request - GuideLine Checklist 

**Guideline** to check code before resolve WIP and approval, respectively.
As many checkboxes as possible should be ticked.

### Checks by code author:
* [x] There is at least one issue associated with the pull request.
* [x] The branch follows the naming conventions as defined in the [git workflow](git-workflow).
* [ ] New code adheres with the [coding guidelines](coding-guidelines)
* [ ] Tests for new functionality has been added
* [ ] A local test was succesful
* [ ] There is appropriate **documentation** of your work. (use doxygen style comments)
* [ ] If new third party software is used, did you pay attention to its license? Please remember to add it to the wiki after successful merging.
* [ ] If new mathematical methods or epidemiological terms are used, has the glossary been updated ? Did you provide further documentation ?
 is present or referenced. Please provide your references.
* [ ] The following questions are addressed in the documentation*:  Developers (what did you do?, how can it be maintained?), For users (how to use your work?), For admins (how to install and configure your work?)
* For documentation: Please write or update the Readme in the current working directory!

### Checks by code reviewer(s):
* [ ] Is the code clean of development artifacts e.g., unnecessary comments, prints, ...
* [ ] The ticket goals for each associated issue are reached or problems are clearly addressed (i.e., a new issue was introduced).
* [ ] There are appropriate **unit tests** and they pass.
* [ ] The git history is clean and linearized for the merge request.
* [ ] Coverage report for new code is acceptable.

### CODE REVIEW

**Comment by mknaranja** [comment]
- Plot_results was converted to plot_results_odesecir and can plot results from Kuehn et al, https://doi.org/10.1016/j.mbs.2021.108648
- plot_results_odesecirvvs is the extended script to plot results from Koslow et al, https://doi.org/10.1371/journal.pcbi.1010054

Basically, both tools need to be improved, common functionality should be excluded from particular scripts as well as code for reproduction of the paper plots should be moved to another script.

We should also think of making it a normal python script. What we maybe could do in the future is to provide this functionality in memilio-pycode and to import this in jupyter-notebooks if we want to offer notebooks also in the future.

Furthermore, I want to add some visualization functionality to plot infection (or other) data on maps. This will be done within this merge request.

**Comment by mknaranja** [comment]
@HenrZu lets discuss tomorrow if we extract the open points to new issues to bring this to the main soon.

**Comment by mknaranja** [comment]
I created #355 and #356 for the remaining tasks

**Review by HenrZu — APPROVED** [review]
Looks good for now.
In any case, a few updates are still necessary here, which we will work on in the issues you mentioned.

**Pull request merged**
